title: Recursos abiertos de la Licenciatura en Sociología de UFLO
description: Un listado de algunos recursos y materiales didácticos que elaboramos en la carrera de Sociología de la Universidad de Flores (Argentina).
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme